name: Jenkins Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  schedule:
    - cron: '0 0 * * 1'

permissions:
  security-events: write
  contents: read
  actions: read

jobs:
  security-scan:
    # CodeQL upload needs GHAS. Skip until transfer to jenkinsci org.
    if: github.repository_owner == 'jenkinsci'
    uses: jenkins-infra/jenkins-security-scan/.github/workflows/jenkins-security-scan.yaml@v2
    with:
      java-cache: 'maven'
